networks:
  main_network:
    external: true
    name: main_network  # ← добавь эту строку

services:
  bot:
    container_name: service-gudauri-bot
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/home/projects/service-gudauri-bot/logs
      - ./sessions:/app/sessions
    networks:
      - main_network