networks:
  main_network:  # объявляем сеть
    driver: bridge

services:
  bot:
    container_name: service-gudauri-bot
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/home/projects/service-gudauri-bot/logs
      - ./sessions:/app/sessions
    networks:
      - main_network