"""init

Revision ID: 2909a58f6485
Revises: 86e16181719d
Create Date: 2024-12-20 19:21:51.062996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2909a58f6485'
down_revision: Union[str, None] = '86e16181719d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_orders', sa.Column('order_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_orders', 'order_type')
    # ### end Alembic commands ###
