"""init

Revision ID: e11f9eae67a1
Revises: b5e8c53c64a7
Create Date: 2024-12-01 20:27:10.687351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e11f9eae67a1'
down_revision: Union[str, None] = 'b5e8c53c64a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_users', sa.Column('lang', sa.String(), nullable=True))
    op.drop_column('lead_users', 'language')
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('lead_users', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('lead_users', 'lang')
    # ### end Alembic commands ###
