[supervisord]
nodaemon=true

[program:bot]
user=root
directory=/home/mentor-supervisor-bot
command=/home/venvs/mentor-supervisor-bot/bin/python -m src.main
autostart=false
autorestart=true
stderr_logfile=/home/logs/supervisor-bot-stderr.log
stdout_logfile=/home/logs/supervisor-bot-stdout.log

[program:leadbot]
user=root
directory=/home/lead-hunter-bot
command=/home/venvs/lead-hunter-bot/bin/python -m src.main
autostart=false
autorestart=true
stderr_logfile=/home/logs/lead-hunter-bot-stderr.log
stdout_logfile=/home/logs/lead-hunter-bot-stdout.log


[program:sbot]
user=root
directory=/home/service-gudauri-bot
command=/home/venvs/service-gudauri-bot/bin/python -m src.main
autostart=false
autorestart=true
stderr_logfile=/home/logs/service-gudauri-bot-stderr.log
stdout_logfile=/home/logs/service-gudauri-bot-stdout.log